name: Deploy to prod

concurrency: 1

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "**/*.yml"
      - "**/*.py"

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.DBDEMO_DAB_SP_AZURE_CREDENTIALS_JSON }}'

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DBDEMO_DAB_SP_PAT }}
          DATABRICKS_BUNDLE_ENV: production

#  pipeline_update:
#    name: "Run pipeline update"
#    runs-on: ubuntu-latest
#
#    needs:
#      - deploy
#
#    steps:
#      - uses: actions/checkout@v3
#      
#      - name: Log in with Azure
#        uses: azure/login@v1
#        with:
#          creds: '${{ secrets.DBDEMO_DAB_SP_AZURE_CREDENTIALS_JSON }}'
#
#     - uses: databricks/setup-cli@main
#
#      - run: databricks bundle run fe_medium_metrics --refresh-all
#        env:
#          DATABRICKS_TOKEN: ${{ secrets.DBDEMO_DAB_SP_PAT }}
#          DATABRICKS_BUNDLE_ENV: production
